#
# Makefile for the video capture/playback device drivers.
#
obj-$(CONFIG_WMT_VIDEO_DECODE) += wmt-vd.o wmt-vdlib.o wmt-dsplib.o wmt-lock.o
obj-$(CONFIG_WMT_VIDEO_DECODE_MPEG2) += mpeg2/
obj-$(CONFIG_WMT_VIDEO_DECODE_MPEG4) += mpeg4/
obj-$(CONFIG_WMT_VIDEO_DECODE_H264) += h264/
obj-$(CONFIG_WMT_VIDEO_DECODE_JPEG) += jpeg/
obj-$(CONFIG_WMT_VIDEO_ENCODE_JPEG) += encode/jpeg/
